[package]
name = "sandbox"
version = "0.1.0"
authors = ["Jon Catanio <joncatanio@gmail.com>"]

[dependencies]
cannolib = { path = "../../../cannolib" }

[profile.release]
debug = true
codegen-units = 1
